//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChelperPro.Resx {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ChelperPro.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string DataLoading {
            get {
                return ResourceManager.GetString("DataLoading", resourceCulture);
            }
        }
        
        internal static string GetStart {
            get {
                return ResourceManager.GetString("GetStart", resourceCulture);
            }
        }
        
        internal static string LaunchingText {
            get {
                return ResourceManager.GetString("LaunchingText", resourceCulture);
            }
        }
        
        internal static string AbCompany {
            get {
                return ResourceManager.GetString("AbCompany", resourceCulture);
            }
        }
        
        internal static string AbVersion {
            get {
                return ResourceManager.GetString("AbVersion", resourceCulture);
            }
        }
        
        internal static string AbDes {
            get {
                return ResourceManager.GetString("AbDes", resourceCulture);
            }
        }
        
        internal static string AbFeedback {
            get {
                return ResourceManager.GetString("AbFeedback", resourceCulture);
            }
        }
        
        internal static string AbContact {
            get {
                return ResourceManager.GetString("AbContact", resourceCulture);
            }
        }
        
        internal static string AbCopyRight {
            get {
                return ResourceManager.GetString("AbCopyRight", resourceCulture);
            }
        }
        
        internal static string ChangePhoto {
            get {
                return ResourceManager.GetString("ChangePhoto", resourceCulture);
            }
        }
        
        internal static string EmailAdd {
            get {
                return ResourceManager.GetString("EmailAdd", resourceCulture);
            }
        }
        
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        internal static string FName {
            get {
                return ResourceManager.GetString("FName", resourceCulture);
            }
        }
        
        internal static string LName {
            get {
                return ResourceManager.GetString("LName", resourceCulture);
            }
        }
        
        internal static string Security {
            get {
                return ResourceManager.GetString("Security", resourceCulture);
            }
        }
        
        internal static string PNumber {
            get {
                return ResourceManager.GetString("PNumber", resourceCulture);
            }
        }
        
        internal static string RePassword {
            get {
                return ResourceManager.GetString("RePassword", resourceCulture);
            }
        }
        
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        internal static string BankInfo {
            get {
                return ResourceManager.GetString("BankInfo", resourceCulture);
            }
        }
        
        internal static string BioText {
            get {
                return ResourceManager.GetString("BioText", resourceCulture);
            }
        }
        
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        internal static string EarnTitle {
            get {
                return ResourceManager.GetString("EarnTitle", resourceCulture);
            }
        }
        
        internal static string CurrentBalance {
            get {
                return ResourceManager.GetString("CurrentBalance", resourceCulture);
            }
        }
        
        internal static string TransferToBank {
            get {
                return ResourceManager.GetString("TransferToBank", resourceCulture);
            }
        }
        
        internal static string Credit {
            get {
                return ResourceManager.GetString("Credit", resourceCulture);
            }
        }
        
        internal static string ExpiryDate {
            get {
                return ResourceManager.GetString("ExpiryDate", resourceCulture);
            }
        }
        
        internal static string CardHolder {
            get {
                return ResourceManager.GetString("CardHolder", resourceCulture);
            }
        }
        
        internal static string CVV {
            get {
                return ResourceManager.GetString("CVV", resourceCulture);
            }
        }
        
        internal static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
        
        internal static string LanguagePreference {
            get {
                return ResourceManager.GetString("LanguagePreference", resourceCulture);
            }
        }
        
        internal static string PriorityLanguage {
            get {
                return ResourceManager.GetString("PriorityLanguage", resourceCulture);
            }
        }
        
        internal static string SecondLanguage {
            get {
                return ResourceManager.GetString("SecondLanguage", resourceCulture);
            }
        }
        
        internal static string Legal {
            get {
                return ResourceManager.GetString("Legal", resourceCulture);
            }
        }
        
        internal static string TermsOfService {
            get {
                return ResourceManager.GetString("TermsOfService", resourceCulture);
            }
        }
        
        internal static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        internal static string RealWordHelp {
            get {
                return ResourceManager.GetString("RealWordHelp", resourceCulture);
            }
        }
        
        internal static string DigitalHelp {
            get {
                return ResourceManager.GetString("DigitalHelp", resourceCulture);
            }
        }
        
        internal static string Inbox {
            get {
                return ResourceManager.GetString("Inbox", resourceCulture);
            }
        }
        
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        internal static string Earn {
            get {
                return ResourceManager.GetString("Earn", resourceCulture);
            }
        }
        
        internal static string Skills {
            get {
                return ResourceManager.GetString("Skills", resourceCulture);
            }
        }
        
        internal static string Select3Skills {
            get {
                return ResourceManager.GetString("Select3Skills", resourceCulture);
            }
        }
        
        internal static string NoAbove {
            get {
                return ResourceManager.GetString("NoAbove", resourceCulture);
            }
        }
        
        internal static string SkillDes {
            get {
                return ResourceManager.GetString("SkillDes", resourceCulture);
            }
        }
        
        internal static string SPrice {
            get {
                return ResourceManager.GetString("SPrice", resourceCulture);
            }
        }
        
        internal static string PriceDes {
            get {
                return ResourceManager.GetString("PriceDes", resourceCulture);
            }
        }
        
        internal static string MySkill {
            get {
                return ResourceManager.GetString("MySkill", resourceCulture);
            }
        }
        
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        internal static string ProblemType {
            get {
                return ResourceManager.GetString("ProblemType", resourceCulture);
            }
        }
        
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        internal static string Transaction {
            get {
                return ResourceManager.GetString("Transaction", resourceCulture);
            }
        }
        
        internal static string Receipt {
            get {
                return ResourceManager.GetString("Receipt", resourceCulture);
            }
        }
        
        internal static string ServiceFee {
            get {
                return ResourceManager.GetString("ServiceFee", resourceCulture);
            }
        }
        
        internal static string Tax {
            get {
                return ResourceManager.GetString("Tax", resourceCulture);
            }
        }
        
        internal static string EquipmentFee {
            get {
                return ResourceManager.GetString("EquipmentFee", resourceCulture);
            }
        }
        
        internal static string CycbisFee {
            get {
                return ResourceManager.GetString("CycbisFee", resourceCulture);
            }
        }
        
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        internal static string CaseInfo {
            get {
                return ResourceManager.GetString("CaseInfo", resourceCulture);
            }
        }
        
        internal static string Emergency {
            get {
                return ResourceManager.GetString("Emergency", resourceCulture);
            }
        }
        
        internal static string DemandList {
            get {
                return ResourceManager.GetString("DemandList", resourceCulture);
            }
        }
        
        internal static string PullDown {
            get {
                return ResourceManager.GetString("PullDown", resourceCulture);
            }
        }
        
        internal static string PriorityArea {
            get {
                return ResourceManager.GetString("PriorityArea", resourceCulture);
            }
        }
        
        internal static string AdditionArea {
            get {
                return ResourceManager.GetString("AdditionArea", resourceCulture);
            }
        }
        
        internal static string AdditionEx {
            get {
                return ResourceManager.GetString("AdditionEx", resourceCulture);
            }
        }
        
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        internal static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        internal static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        internal static string Signout {
            get {
                return ResourceManager.GetString("Signout", resourceCulture);
            }
        }
        
        internal static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        internal static string Safety {
            get {
                return ResourceManager.GetString("Safety", resourceCulture);
            }
        }
        
        internal static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        internal static string ServiceArea {
            get {
                return ResourceManager.GetString("ServiceArea", resourceCulture);
            }
        }
        
        internal static string EnterPhone {
            get {
                return ResourceManager.GetString("EnterPhone", resourceCulture);
            }
        }
        
        internal static string EnterPhoneLabel {
            get {
                return ResourceManager.GetString("EnterPhoneLabel", resourceCulture);
            }
        }
        
        internal static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        internal static string ForgetPassword {
            get {
                return ResourceManager.GetString("ForgetPassword", resourceCulture);
            }
        }
        
        internal static string SMSVerify {
            get {
                return ResourceManager.GetString("SMSVerify", resourceCulture);
            }
        }
        
        internal static string SMSVerifyLabel {
            get {
                return ResourceManager.GetString("SMSVerifyLabel", resourceCulture);
            }
        }
        
        internal static string ResendCode {
            get {
                return ResourceManager.GetString("ResendCode", resourceCulture);
            }
        }
        
        internal static string Old {
            get {
                return ResourceManager.GetString("Old", resourceCulture);
            }
        }
        
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        internal static string SSN {
            get {
                return ResourceManager.GetString("SSN", resourceCulture);
            }
        }
        
        internal static string SSNLabel {
            get {
                return ResourceManager.GetString("SSNLabel", resourceCulture);
            }
        }
        
        internal static string SkillPageQ1 {
            get {
                return ResourceManager.GetString("SkillPageQ1", resourceCulture);
            }
        }
        
        internal static string SkillPageQ2 {
            get {
                return ResourceManager.GetString("SkillPageQ2", resourceCulture);
            }
        }
    }
}
